%{?!ros_distro:%global ros_distro rolling}
%global pkg_name ecal
%global normalized_pkg_name %{lua:return (string.gsub(rpm.expand('%{pkg_name}'), '_', '-'))}

Name:           ros-rolling-ecal
Version:        5.12.0
Release:        4%{?dist}
Summary:        ROS %{pkg_name} package

License:        Apache 2.0
URL:            https://eclipse-ecal.github.io/ecal
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  bloom-rpm-macros
BuildRequires:  cmake

%{?bloom_package}

%description
eCAL - enhanced Communication Abstraction Layer. A fast publish-subscribe cross-
plattform middleware using Shared Memory and UDP.


%package devel
Release:        %{release}%{?release_suffix}
Summary:        %{summary}
Provides:       %{name} = %{version}-%{release}
Provides:       %{name}%{?_isa} = %{version}-%{release}
Requires:       %{name}-runtime%{?_isa} = %{version}-%{release}

%description devel
eCAL - enhanced Communication Abstraction Layer. A fast publish-subscribe cross-
plattform middleware using Shared Memory and UDP.


%package runtime
Release:        %{release}
Summary:        %{summary}

%description runtime
eCAL - enhanced Communication Abstraction Layer. A fast publish-subscribe cross-
plattform middleware using Shared Memory and UDP.


%prep
%autosetup -p1


%generate_buildrequires
%bloom_buildrequires


%build
%cmake \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="%{bloom_prefix}" \
    -DCMAKE_PREFIX_PATH="%{bloom_prefix}" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif

%cmake3_build


%install
%cmake_install


%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C %{__cmake_builddir} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
CTEST_OUTPUT_ON_FAILURE=1 \
    %cmake_build $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif


%files devel
%ghost %{bloom_prefix}/share/%{pkg_name}/package.xml


%files runtime
%{bloom_prefix}


%changelog
* Thu Mar 21 2024 Eclipse Foundation, Inc. <ecal-dev@eclipse.org> - 5.12.0-4
- Autogenerated by Bloom
